// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase Database Configuration for FYP
// Use environment variables or fallback to demo database
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || import.meta.env.NEXT_PUBLIC_SUPABASE_URL || "https://djnrvyyassoosqtaoynk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqbnJ2eXlhc3Nvb3NxdGFveW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTQ3NDcsImV4cCI6MjA2ODU5MDc0N30.87aY2QQRftLDMDKuOU2ZgzfYwO9V9JZKoc0ZR8OogUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Development mode flag - check environment variable
export const isDevelopmentMode = false; // Force to use real database